//! Binary-level tests for native zsh profile planning commands.

use std::path::PathBuf;
use std::process::{Command, Output};

fn winuxsh_binary() -> PathBuf {
    let p = PathBuf::from(env!("CARGO_BIN_EXE_winuxsh"));
    if p.exists() {
        return p;
    }

    let mut fallback = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    fallback.push("target");
    fallback.push("debug");
    fallback.push(if cfg!(windows) {
        "winuxsh.exe"
    } else {
        "winuxsh"
    });
    fallback
}

#[test]
fn zsh_profile_plan_agent_is_quiet_and_deterministic() {
    let output = run_winuxsh(&["--zsh-profile-plan", "agent"]);
    assert_success(&output, "zsh profile plan agent");
    let stdout = stdout_text(&output);

    assert!(stdout.contains("# Generated by winuxsh --zsh-profile-plan agent"));
    assert!(stdout.contains("auto_apply = false"));
    assert!(stdout.contains("import_zshrc = false"));
    assert!(stdout.contains("plugins = []"));
    assert!(stdout.contains("[zsh.native_widgets]\nenabled = false"));
    assert!(stdout.contains("[zsh.native_plugins]\nenabled = false"));
    assert!(!stdout.contains("\"git\""));
}

#[test]
fn zsh_profile_plan_zsh_lite_enables_git_and_widgets_only() {
    let output = run_winuxsh(&["--zsh-profile-plan", "zsh-lite"]);
    assert_success(&output, "zsh profile plan zsh-lite");
    let stdout = stdout_text(&output);

    assert!(stdout.contains("# Generated by winuxsh --zsh-profile-plan zsh-lite"));
    assert!(stdout.contains("auto_apply = true"));
    assert!(stdout.contains(
        "plugins = [\"git\", \"zsh-autosuggestions\", \"zsh-history-substring-search\"]"
    ));
    assert!(stdout.contains("[zsh.native_widgets]\nenabled = true"));
    assert!(stdout.contains("presets = [\"autosuggestions\", \"history_substring_search\"]"));
    assert!(stdout.contains("[zsh.native_plugins]\nenabled = false"));
    assert!(stdout.contains("[zsh.dynamic_completions]\nenabled = false"));
    assert!(stdout.contains("[zsh.runtime_completions]\nenabled = false"));
}

#[test]
fn zsh_profile_plan_rejects_unknown_profile() {
    let output = run_winuxsh(&["--zsh-profile-plan", "full"]);

    assert!(!output.status.success());
    assert!(stderr_text(&output).contains("unknown zsh profile"));
}

fn run_winuxsh(args: &[&str]) -> Output {
    Command::new(winuxsh_binary())
        .args(args)
        .output()
        .unwrap_or_else(|err| panic!("failed to run winuxsh {args:?}: {err}"))
}

fn assert_success(output: &Output, context: &str) {
    assert!(
        output.status.success(),
        "{context} failed: status={:?}\nstdout={}\nstderr={}",
        output.status.code(),
        stdout_text(output),
        stderr_text(output)
    );
}

fn stdout_text(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).replace("\r\n", "\n")
}

fn stderr_text(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).replace("\r\n", "\n")
}
