// bash_import.rs
//
// Parses bash completion scripts (typically generated by clap / cobra tools)
// into the same `CommandDef` structure used by `.toml` definition files.
//
// Recognised patterns (generated by `clap_complete` / similar):
//
//   opts="--flag1 -f --flag2 ..."
//       → enumerates every flag the command accepts
//
//   case "${prev}" in
//     --flag|--alias)
//         COMPREPLY=($(compgen -W "a b c" -- "${cur}"))   → static values
//         ;;
//     --other)
//         COMPREPLY=($(compgen -f "${cur}"))               → path completion
//         ;;
//   esac
//
// Pairing rule: a short flag and a long flag are merged into a single FlagDef
// only when they both appear in the case block with *identical* static value
// lists. Path-type flags are never auto-paired (they are indistinguishable in
// bash scripts) and are emitted as separate entries.

use std::collections::{HashMap, HashSet};
use std::path::Path;

use crate::completion::external::{CommandDef, FlagDef, PathLiteral, ValuesSource};

// ─────────────────────────────────────────────────────────────────────────────
// Public entry-point
// ─────────────────────────────────────────────────────────────────────────────

/// Parse a bash completion script at `path` and return a `CommandDef`.
///
/// The command name is derived from the file stem (stripping a leading `_`),
/// so `_fd.bash` → `fd`, `fd.bash` → `fd`.
pub fn parse_bash_completion(path: &Path) -> Result<CommandDef, String> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| format!("read error: {}", e))?;

    let cmd_name = path
        .file_stem()
        .and_then(|s| s.to_str())
        .map(|s| s.trim_start_matches('_').to_string())
        .ok_or_else(|| "cannot derive command name from file path".to_string())?;

    let all_flags = extract_opts_flags(&content);
    let case_info = parse_case_block(&content);
    let flags = build_flag_defs(&all_flags, &case_info);

    Ok(CommandDef {
        command: cmd_name,
        description: None,
        flags,
        subcommands: vec![],
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// Internal value-type enum (not exposed publicly)
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
enum FlagValueInfo {
    Static(Vec<String>),
    Path,
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 1 – extract all flags from the `opts="..."` line
// ─────────────────────────────────────────────────────────────────────────────

fn extract_opts_flags(content: &str) -> Vec<String> {
    // The opts string may contain newlines in some generators; scan the raw
    // content for ALL `opts="..."` blocks and pick the one with actual flags.
    // Many bash completion scripts initialise with `opts=""` before setting
    // the real value, so we need to skip empty assignments.
    let marker = "opts=\"";
    let mut best: Vec<String> = vec![];

    let mut search_start = 0;
    while let Some(rel) = content[search_start..].find(marker) {
        let start = search_start + rel + marker.len();
        let rest = &content[start..];
        let end = match rest.find('"') {
            Some(pos) => pos,
            None => break,
        };

        let flags: Vec<String> = rest[..end]
            .split_whitespace()
            .filter(|tok| tok.starts_with('-'))
            .map(|tok| tok.to_string())
            .collect();

        if flags.len() > best.len() {
            best = flags;
        }

        search_start = start + end + 1;
    }

    best
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 2 – parse `case "${prev}" in … esac`
// ─────────────────────────────────────────────────────────────────────────────

fn parse_case_block(content: &str) -> HashMap<String, FlagValueInfo> {
    let mut result: HashMap<String, FlagValueInfo> = HashMap::new();
    let mut in_case = false;
    let mut cur_flags: Vec<String> = vec![];

    for line in content.lines() {
        let trimmed = line.trim();

        // Entry into the prev-checking case block
        if !in_case {
            if trimmed.contains("case \"${prev}\"") || trimmed.contains("case \"$prev\"") {
                in_case = true;
            }
            continue;
        }

        // End of block
        if trimmed == "esac" {
            break;
        }

        // Wildcard arm – reset flag accumulator
        if trimmed.starts_with("*)") {
            cur_flags.clear();
            continue;
        }

        // Case arm: `--flag)` or `--flag1|--flag2|-f)`
        // Must end with `)` and contain at least one dash-prefixed token
        if trimmed.ends_with(')') && !trimmed.starts_with("COMPREPLY") {
            let arm = trimmed.trim_end_matches(')');
            let candidates: Vec<String> = arm
                .split('|')
                .map(|s| s.trim().to_string())
                .filter(|s| s.starts_with('-'))
                .collect();
            if !candidates.is_empty() {
                cur_flags = candidates;
                continue;
            }
        }

        if cur_flags.is_empty() {
            continue;
        }

        // compgen -W "a b c ..."  → static values
        if trimmed.contains("compgen -W \"") {
            if let Some(w_pos) = trimmed.find("compgen -W \"") {
                let rest = &trimmed[w_pos + 12..]; // skip `compgen -W "`
                if let Some(close) = rest.find('"') {
                    let vals: Vec<String> = rest[..close]
                        .split_whitespace()
                        .filter(|s| !s.is_empty())
                        .map(|s| s.to_string())
                        .collect();
                    for f in &cur_flags {
                        result.insert(f.clone(), FlagValueInfo::Static(vals.clone()));
                    }
                    cur_flags.clear();
                    continue;
                }
            }
        }

        // compgen -f  (files) / compgen -d (dirs) → path completion
        if trimmed.contains("compgen -f") || trimmed.contains("compgen -d") {
            for f in &cur_flags {
                result.insert(f.clone(), FlagValueInfo::Path);
            }
            cur_flags.clear();
            continue;
        }

        // return 0 / ;; → end of arm body, reset accumulator
        if trimmed == ";;" || trimmed.starts_with("return") {
            cur_flags.clear();
        }
    }

    result
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 3 – build FlagDef list
// ─────────────────────────────────────────────────────────────────────────────

fn build_flag_defs(
    all_flags: &[String],
    case_info: &HashMap<String, FlagValueInfo>,
) -> Vec<FlagDef> {
    let long_flags: Vec<&String> = all_flags.iter().filter(|s| s.starts_with("--")).collect();
    let short_flags: Vec<&String> = all_flags
        .iter()
        .filter(|s| s.starts_with('-') && !s.starts_with("--"))
        .collect();

    let mut used_short: HashSet<&str> = HashSet::new();
    let mut result: Vec<FlagDef> = Vec::new();

    // Long flags first — attempt to find a matching short alias
    for long in &long_flags {
        let val_info = case_info.get(*long);

        // Only pair when both flags have IDENTICAL static value lists.
        // Path-type flags are never paired automatically.
        let matched_short: Option<&str> = if let Some(FlagValueInfo::Static(vals)) = val_info {
            short_flags.iter().find_map(|&&ref short| {
                if used_short.contains(short.as_str()) {
                    return None;
                }
                if let Some(FlagValueInfo::Static(sv)) = case_info.get(short) {
                    if sv == vals {
                        return Some(short.as_str());
                    }
                }
                None
            })
        } else {
            None
        };

        if let Some(short) = matched_short {
            used_short.insert(short);
        }

        result.push(make_flag_def(
            matched_short.map(|s| s.to_string()),
            Some((*long).clone()),
            val_info,
        ));
    }

    // Short flags not paired with any long flag
    for short in &short_flags {
        if used_short.contains(short.as_str()) {
            continue;
        }
        let val_info = case_info.get(*short);
        result.push(make_flag_def(Some((*short).clone()), None, val_info));
    }

    result
}

fn make_flag_def(
    short: Option<String>,
    long: Option<String>,
    val_info: Option<&FlagValueInfo>,
) -> FlagDef {
    match val_info {
        Some(FlagValueInfo::Static(vals)) => FlagDef {
            short,
            long,
            description: None,
            takes_value: true,
            values_source: Some(ValuesSource::Static {
                values: vals.clone(),
            }),
        },
        Some(FlagValueInfo::Path) => FlagDef {
            short,
            long,
            description: None,
            takes_value: true,
            values_source: Some(ValuesSource::Path {
                values_from: PathLiteral,
            }),
        },
        None => FlagDef {
            short,
            long,
            description: None,
            takes_value: false,
            values_source: None,
        },
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"
_mytool() {
    local opts
    opts="-h -V --help --version --type --color"
    case "${prev}" in
        --type|-t)
            COMPREPLY=($(compgen -W "file dir symlink" -- "${cur}"))
            return 0
            ;;
        --color)
            COMPREPLY=($(compgen -W "auto always never" -- "${cur}"))
            return 0
            ;;
        --output)
            COMPREPLY=($(compgen -f "${cur}"))
            return 0
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}
"#;

    #[test]
    fn test_extract_opts() {
        let flags = extract_opts_flags(SAMPLE);
        assert!(flags.contains(&"--help".to_string()));
        assert!(flags.contains(&"--type".to_string()));
        assert!(flags.contains(&"-h".to_string()));
    }

    #[test]
    fn test_case_static() {
        let info = parse_case_block(SAMPLE);
        assert_eq!(
            info.get("--color"),
            Some(&FlagValueInfo::Static(vec![
                "auto".to_string(),
                "always".to_string(),
                "never".to_string()
            ]))
        );
    }

    #[test]
    fn test_case_path() {
        let info = parse_case_block(SAMPLE);
        assert_eq!(info.get("--output"), Some(&FlagValueInfo::Path));
    }

    #[test]
    fn test_pairing_same_static() {
        // --type and implicit -t are NOT in opts here, so just verify no crash
        let flags = extract_opts_flags(SAMPLE);
        let info = parse_case_block(SAMPLE);
        let defs = build_flag_defs(&flags, &info);
        // --color should have static values
        let color_def = defs.iter().find(|d| d.long.as_deref() == Some("--color"));
        assert!(color_def.is_some());
        assert!(color_def.unwrap().takes_value);
    }
}
