command = "cat"
description = "concatenate files and print on the standard output"

[[flags]]
short = "-A"
long = "--show-all"
description = "equivalent to -vET"

[[flags]]
short = "-b"
long = "--number-nonblank"
description = "number nonempty output lines, overrides -n"

[[flags]]
short = "-e"
description = "equivalent to -vE"

[[flags]]
short = "-E"
long = "--show-ends"
description = "display $ at end of each line"

[[flags]]
short = "-n"
long = "--number"
description = "number all output lines"

[[flags]]
short = "-s"
long = "--squeeze-blank"
description = "suppress repeated empty output lines"

[[flags]]
short = "-t"
description = "equivalent to -vT"

[[flags]]
short = "-T"
long = "--show-tabs"
description = "display TAB characters as ^I"

[[flags]]
short = "-u"
description = "ignored, for POSIX compatibility"

[[flags]]
short = "-v"
long = "--show-nonprinting"
description = "use ^ and M- notation, except for LFD and TAB"
