command = "chmod"
description = "change file mode bits"

[[flags]]
short = "-c"
long = "--changes"
description = "like verbose but report only when a change is made"

[[flags]]
short = "-f"
long = "--silent"
description = "suppress most error messages"

[[flags]]
long = "--quiet"
description = "suppress most error messages"

[[flags]]
short = "-v"
long = "--verbose"
description = "output a diagnostic for every file processed"

[[flags]]
short = "-R"
long = "--recursive"
description = "change files and directories recursively"

[[flags]]
long = "--reference"
description = "use RFILE's mode instead of MODE values"
takes_value = true
values_from = "path"

[[flags]]
short = "-H"
description = "traverse command-line symlinks to directories"

[[flags]]
short = "-L"
description = "traverse every symlink to a directory"

[[flags]]
short = "-P"
description = "do not traverse any symbolic links"

[[flags]]
long = "--dereference"
description = "affect the referent of each symbolic link"

[[flags]]
long = "--preserve-root"
description = "fail to operate recursively on /"

[[flags]]
long = "--no-preserve-root"
description = "do not treat / specially"
