command = "cp"
description = "copy files and directories"

[[flags]]
short = "-a"
long = "--archive"
description = "same as -dR --preserve=all"

[[flags]]
short = "-b"
description = "like --backup but does not accept an argument"

[[flags]]
long = "--backup"
description = "make a backup of each existing destination file"

[[flags]]
short = "-d"
description = "same as --no-dereference --preserve=links"

[[flags]]
short = "-f"
long = "--force"
description = "if an existing destination file cannot be opened, remove it and try again"

[[flags]]
short = "-i"
long = "--interactive"
description = "prompt before overwrite"

[[flags]]
short = "-H"
description = "follow command-line symbolic links in SOURCE"

[[flags]]
short = "-l"
long = "--link"
description = "hard link files instead of copying"

[[flags]]
short = "-L"
long = "--dereference"
description = "always follow symbolic links in SOURCE"

[[flags]]
short = "-n"
long = "--no-clobber"
description = "do not overwrite an existing file and do not fail"

[[flags]]
short = "-P"
long = "--no-dereference"
description = "never follow symbolic links in SOURCE"

[[flags]]
short = "-p"
description = "same as --preserve=mode,ownership,timestamps"

[[flags]]
short = "-R"
long = "--recursive"
description = "copy directories recursively"

[[flags]]
short = "-r"
long = "--recursive"
description = "copy directories recursively"

[[flags]]
short = "-s"
long = "--symbolic-link"
description = "make symbolic links instead of copying"

[[flags]]
short = "-S"
long = "--suffix"
description = "override the usual backup suffix"
takes_value = true

[[flags]]
short = "-t"
long = "--target-directory"
description = "copy all SOURCE arguments into DIRECTORY"
takes_value = true
values_from = "path"

[[flags]]
short = "-T"
long = "--no-target-directory"
description = "treat DEST as a normal file"

[[flags]]
short = "-u"
long = "--update"
description = "equivalent to --update[=older]"

[[flags]]
short = "-v"
long = "--verbose"
description = "explain what is being done"

[[flags]]
short = "-x"
long = "--one-file-system"
description = "stay on this file system"

[[flags]]
long = "--preserve"
description = "preserve the specified attributes"
takes_value = true
values = ["mode", "ownership", "timestamps", "links", "context", "xattr", "all"]

[[flags]]
long = "--no-preserve"
description = "do not preserve the specified attributes"
takes_value = true
values = ["mode", "ownership", "timestamps", "links", "context", "xattr", "all"]
