command = "find"
description = "search for files in a directory hierarchy"

[[flags]]
short = "-name"
description = "base of file name matches shell pattern PATTERN"
takes_value = true

[[flags]]
short = "-iname"
description = "like -name, but case insensitive"
takes_value = true

[[flags]]
short = "-path"
description = "file name matches shell pattern PATTERN"
takes_value = true

[[flags]]
short = "-ipath"
description = "like -path, but case insensitive"
takes_value = true

[[flags]]
short = "-type"
description = "file is of type d, f, or l"
takes_value = true
values = ["f", "d", "l"]

[[flags]]
short = "-size"
description = "file uses n units of space"
takes_value = true

[[flags]]
short = "-empty"
description = "file is empty and is either a regular file or a directory"

[[flags]]
short = "-mtime"
description = "file data was last modified n*24 hours ago"
takes_value = true

[[flags]]
short = "-mmin"
description = "file data was last modified n minutes ago"
takes_value = true

[[flags]]
short = "-mindepth"
description = "descend at least LEVELS levels before tests"
takes_value = true

[[flags]]
short = "-maxdepth"
description = "descend at most LEVELS levels below starting-points"
takes_value = true

[[flags]]
short = "-print"
description = "print the full file name on standard output"

[[flags]]
short = "-print0"
description = "print the full file name followed by a null character"

[[flags]]
short = "-delete"
description = "delete files"

[[flags]]
short = "-exec"
description = "execute command"
takes_value = true

[[flags]]
short = "-regex"
description = "whole path matches regular expression"
takes_value = true

[[flags]]
short = "-iregex"
description = "whole path matches regular expression, case insensitive"
takes_value = true
