command = "grep"
description = "search for patterns in each file"

[[flags]]
short = "-i"
long = "--ignore-case"
description = "ignore case distinctions in patterns and data"

[[flags]]
short = "-e"
long = "--regexp"
description = "use PATTERNS for matching"
takes_value = true

[[flags]]
short = "-f"
long = "--file"
description = "take PATTERNS from FILE"
takes_value = true
values_from = "path"

[[flags]]
short = "-r"
long = "--recursive"
description = "like --directories=recurse"

[[flags]]
short = "-n"
long = "--line-number"
description = "print line number with output lines"

[[flags]]
short = "-c"
long = "--count"
description = "print only a count of selected lines per FILE"

[[flags]]
short = "-v"
long = "--invert-match"
description = "select non-matching lines"

[[flags]]
short = "-F"
long = "--fixed-strings"
description = "PATTERNS are strings"

[[flags]]
short = "-E"
long = "--extended-regexp"
description = "PATTERNS are extended regular expressions"

[[flags]]
short = "-w"
long = "--word-regexp"
description = "match only whole words"

[[flags]]
short = "-x"
long = "--line-regexp"
description = "match only whole lines"

[[flags]]
long = "--color"
description = "highlight matching strings; WHEN can be 'always', 'never', or 'auto'"
takes_value = true
values = ["always", "auto", "never"]

[[flags]]
long = "--include"
description = "search only files that match GLOB"
takes_value = true

[[flags]]
long = "--exclude"
description = "skip files that match GLOB"
takes_value = true

[[flags]]
long = "--exclude-dir"
description = "skip directories that match GLOB"
takes_value = true
