command = "mkdir"
description = "make directories"

[[flags]]
short = "-m"
long = "--mode"
description = "set file mode"
takes_value = true

[[flags]]
short = "-p"
long = "--parents"
description = "no error if existing, make parent directories as needed"

[[flags]]
short = "-v"
long = "--verbose"
description = "print a message for each created directory"

[[flags]]
short = "-Z"
long = "--context"
description = "set SELinux security context of each created directory"
takes_value = true
