command = "touch"
description = "change file timestamps"

[[flags]]
short = "-a"
description = "change only the access time"

[[flags]]
short = "-c"
long = "--no-create"
description = "do not create any files"

[[flags]]
short = "-d"
long = "--date"
description = "parse STRING and use it instead of current time"
takes_value = true

[[flags]]
short = "-f"
description = "ignored"

[[flags]]
short = "-h"
long = "--no-dereference"
description = "affect symbolic link instead of referenced file"

[[flags]]
short = "-m"
description = "change only the modification time"

[[flags]]
short = "-r"
long = "--reference"
description = "use this file's times instead of current time"
takes_value = true
values_from = "path"

[[flags]]
short = "-t"
description = "use [[CC]YY]MMDDhhmm[.ss] instead of current time"
takes_value = true

[[flags]]
long = "--time"
description = "change the specified time"
takes_value = true
values = ["access", "atime", "use", "modify", "mtime"]
